package domain;
// Generated 2018-3-22 15:48:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DcData generated by hbm2java
 */
public class DcData implements java.io.Serializable {

	private Date date;
	private Integer sales;
	private Integer totalnum;

	public DcData() {
	}

	public DcData(Date date) {
		this.date = date;
	}

	public DcData(Date date, Integer sales, Integer totalnum) {
		this.date = date;
		this.sales = sales;
		this.totalnum = totalnum;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getSales() {
		return this.sales;
	}

	public void setSales(Integer sales) {
		this.sales = sales;
	}

	public Integer getTotalnum() {
		return this.totalnum;
	}

	public void setTotalnum(Integer totalnum) {
		this.totalnum = totalnum;
	}

}
