// default package
// Generated 2018-3-22 15:48:22 by Hibernate Tools 3.4.0.CR1
package domain;
/**
 * DcOrdercontent generated by hbm2java
 */
public class DcOrdercontent implements java.io.Serializable {

	private Integer ocId;
	private DcDish dcDish;
	private DcOrder dcOrder;
	private int ocDishNumber;

	public DcOrdercontent() {
	}

	public DcOrdercontent(DcDish dcDish, DcOrder dcOrder, int ocDishNumber) {
		this.dcDish = dcDish;
		this.dcOrder = dcOrder;
		this.ocDishNumber = ocDishNumber;
	}

	public Integer getOcId() {
		return this.ocId;
	}

	public void setOcId(Integer ocId) {
		this.ocId = ocId;
	}

	public DcDish getDcDish() {
		return this.dcDish;
	}

	public void setDcDish(DcDish dcDish) {
		this.dcDish = dcDish;
	}

	public DcOrder getDcOrder() {
		return this.dcOrder;
	}

	public void setDcOrder(DcOrder dcOrder) {
		this.dcOrder = dcOrder;
	}

	public int getOcDishNumber() {
		return this.ocDishNumber;
	}

	public void setOcDishNumber(int ocDishNumber) {
		this.ocDishNumber = ocDishNumber;
	}

}
