// default package
// Generated 2018-3-22 15:48:22 by Hibernate Tools 3.4.0.CR1
package domain;
import java.util.HashSet;
import java.util.Set;

/**
 * DcOrderstate generated by hbm2java
 */
public class DcOrderstate implements java.io.Serializable {

	private Integer osId;
	private String osName;
	private Set dcOrders = new HashSet(0);

	public DcOrderstate() {
	}

	public DcOrderstate(String osName) {
		this.osName = osName;
	}

	public DcOrderstate(String osName, Set dcOrders) {
		this.osName = osName;
		this.dcOrders = dcOrders;
	}

	public Integer getOsId() {
		return this.osId;
	}

	public void setOsId(Integer osId) {
		this.osId = osId;
	}

	public String getOsName() {
		return this.osName;
	}

	public void setOsName(String osName) {
		this.osName = osName;
	}

	public Set getDcOrders() {
		return this.dcOrders;
	}

	public void setDcOrders(Set dcOrders) {
		this.dcOrders = dcOrders;
	}

}
