// default package
// Generated 2018-3-22 15:48:22 by Hibernate Tools 3.4.0.CR1
package domain;
/**
 * DcTable generated by hbm2java
 */
public class DcTable implements java.io.Serializable {

	private Integer TId;
	private char TIsFree;
	private int TSize;

	public DcTable() {
	}

	public DcTable(char TIsFree, int TSize) {
		this.TIsFree = TIsFree;
		this.TSize = TSize;
	}

	public Integer getTId() {
		return this.TId;
	}

	public void setTId(Integer TId) {
		this.TId = TId;
	}

	public char getTIsFree() {
		return this.TIsFree;
	}

	public void setTIsFree(char TIsFree) {
		this.TIsFree = TIsFree;
	}

	public int getTSize() {
		return this.TSize;
	}

	public void setTSize(int TSize) {
		this.TSize = TSize;
	}

}
