// default package
// Generated 2018-3-22 15:48:22 by Hibernate Tools 3.4.0.CR1
package domain;
import java.util.HashSet;
import java.util.Set;

/**
 * DcUserposition generated by hbm2java
 */
public class DcUserposition implements java.io.Serializable {

	private Integer upId;
	private String upName;
	private Set dcUsers = new HashSet(0);

	public DcUserposition() {
	}

	public DcUserposition(String upName) {
		this.upName = upName;
	}

	public DcUserposition(String upName, Set dcUsers) {
		this.upName = upName;
		this.dcUsers = dcUsers;
	}

	public Integer getUpId() {
		return this.upId;
	}

	public void setUpId(Integer upId) {
		this.upId = upId;
	}

	public String getUpName() {
		return this.upName;
	}

	public void setUpName(String upName) {
		this.upName = upName;
	}

	public Set getDcUsers() {
		return this.dcUsers;
	}

	public void setDcUsers(Set dcUsers) {
		this.dcUsers = dcUsers;
	}

}
