// default package
// Generated 2018-3-22 15:48:22 by Hibernate Tools 3.4.0.CR1
package domain;
/**
 * DcUser generated by hbm2java
 */
public class DcUser implements java.io.Serializable {

	private Integer UId;
	private DcUserposition dcUserposition;
	private String UAccount;
	private String UPwd;
	private char UIsLocked;
	private String UFaceImg;
	private String UName;
	private char USex;
	private String UPhoneNumber;
	private String UAddress;

	public DcUser() {
	}

	public DcUser(DcUserposition dcUserposition, String UAccount, String UPwd, char UIsLocked, String UName,
			char USex) {
		this.dcUserposition = dcUserposition;
		this.UAccount = UAccount;
		this.UPwd = UPwd;
		this.UIsLocked = UIsLocked;
		this.UName = UName;
		this.USex = USex;
	}

	public DcUser(DcUserposition dcUserposition, String UAccount, String UPwd, char UIsLocked, String UFaceImg,
			String UName, char USex, String UPhoneNumber, String UAddress) {
		this.dcUserposition = dcUserposition;
		this.UAccount = UAccount;
		this.UPwd = UPwd;
		this.UIsLocked = UIsLocked;
		this.UFaceImg = UFaceImg;
		this.UName = UName;
		this.USex = USex;
		this.UPhoneNumber = UPhoneNumber;
		this.UAddress = UAddress;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public DcUserposition getDcUserposition() {
		return this.dcUserposition;
	}

	public void setDcUserposition(DcUserposition dcUserposition) {
		this.dcUserposition = dcUserposition;
	}

	public String getUAccount() {
		return this.UAccount;
	}

	public void setUAccount(String UAccount) {
		this.UAccount = UAccount;
	}

	public String getUPwd() {
		return this.UPwd;
	}

	public void setUPwd(String UPwd) {
		this.UPwd = UPwd;
	}

	public char getUIsLocked() {
		return this.UIsLocked;
	}

	public void setUIsLocked(char UIsLocked) {
		this.UIsLocked = UIsLocked;
	}

	public String getUFaceImg() {
		return this.UFaceImg;
	}

	public void setUFaceImg(String UFaceImg) {
		this.UFaceImg = UFaceImg;
	}

	public String getUName() {
		return this.UName;
	}

	public void setUName(String UName) {
		this.UName = UName;
	}

	public char getUSex() {
		return this.USex;
	}

	public void setUSex(char USex) {
		this.USex = USex;
	}

	public String getUPhoneNumber() {
		return this.UPhoneNumber;
	}

	public void setUPhoneNumber(String UPhoneNumber) {
		this.UPhoneNumber = UPhoneNumber;
	}

	public String getUAddress() {
		return this.UAddress;
	}

	public void setUAddress(String UAddress) {
		this.UAddress = UAddress;
	}

}
